### ISSUE TITLE
2d vector class

### ISSUE THREAD

**Issue by martinjrobins** [trase-cpp/trase#13]
currently using `std::array<float,2>` for 2d vectors, should do a proper 2d vector class that can do common vector operations in order to make the code more readable

**Comment by martinjrobins** [comment]
many clang tidy errors are coming from this class: need to clean these up

**Comment by fcooper8472** [comment]
Yeah, agreed.  I think that core guideline might be more for library users than library writers.  As long as we're well unit-tested I would be happy to turn off `cppcoreguidelines-pro-bounds-constant-array-index`.

**Comment by fcooper8472** [comment]
I would like to propose adding iterators to the Vector class.  This would allow us to:
* Traverse vectors with a range-for loop
* Use stl algorithms

Both of these could be used to tidy up the internals (e.g. `std::fill_n` instead of a raw loop for the one-arg constructor).

**Comment by fcooper8472** [comment]
Also, let's add some unit tests for the vector functionality.

**Comment by martinjrobins** [comment]
I'm happy to put in some bounds checking, as long as there is no cost in Release mode (i.e. static_asserts asserts). 

Iterators and use of the stl algorithms is a great idea. I was thinking of replacing the raw C array with a `std::array` anyway (this is in PR #25), so you can also just directly use STL algorithm on that.
