### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by fcooper8472** [trase-cpp/trase#139]
Move CI to GitHub actions and add more checks

**Comment by fcooper8472** [comment]
There are some genuine issues with svg validation, and with compilation on Windows.

**Comment by fcooper8472** [comment]
@martinjrobins a few for you please:

- deactivate [appveyor](https://ci.appveyor.com/project/martinjrobins/trase-ra1n2/branch/master)
- I don't have permission to add secrets - could you regenerate the codecov token, and add it as a secret with key `CODECOV_TOKEN`

**Comment by fcooper8472** [comment]
I also can't figure out what Windows is complaining about....

**Comment by martinjrobins** [comment]
> @martinjrobins a few for you please:
> 
> * deactivate [appveyor](https://ci.appveyor.com/project/martinjrobins/trase-ra1n2/branch/master)
> * I don't have permission to add secrets - could you regenerate the codecov token, and add it as a secret with key `CODECOV_TOKEN`

Done, I've given you admin permissions on the repo as well

**Comment by fcooper8472** [comment]
Thanks!

Looks as though you'll have to deactivate Travis as well.

**Comment by fcooper8472** [comment]
The problem was a trase `operator[]` that takes an int rather than the usual `size_t` - but I think this might be required, so I've just added some more `static_cast`s.

Two things left now:

1. Update readme with new badges
1. CMake on GitHub actions isn't finding curl, so coverage is down...

**Comment by martinjrobins** [comment]
Fixed via #140
