### ISSUE TITLE
ylabel overlaps with the yticks

### ISSUE THREAD

**Issue by zhongjingjogy** [trase-cpp/trase#146]
Thanks for the nice open source implementation for plotting with C++.

I am trying trase to visualize a series x-y points. It seems that ylabel overlaps with the yticks. It would be great if hints and useful suggestions are available. The result looks likes as follow
![test_demo](https://user-images.githubusercontent.com/9261231/180094379-7e0556ec-5a99-4da9-b1c9-a5f1e8d8793b.svg)

The code for reproducing the demo comes as
```
#include "trase.hpp"
#include <iostream>
#include <fstream>

using namespace trase;

int main() {
    std::string dest = "test_demo.svg";

    std::vector<double> predicted_data = {
        -13.8881, -13.8671, -13.8361, -13.7881, -13.7681, -13.7381, -12.6881, -12.661, -12.6481
    };
    std::vector<double> exp_data = {
        -13.8881, -13.8671, -13.8361, -13.7881, -13.7681, -13.7381, -12.6881, -12.661, -12.6481
    };

    auto fig = figure();
    auto ax = fig->axis();
    int predicted_size = predicted_data.size();
    int exp_size = exp_data.size();

    std::vector<float> x(predicted_size);
    std::vector<float> y(exp_size);
    for (int i = 0; i < predicted_size; ++i) {
        x[i] = predicted_data[i];
    }
    for (int i = 0; i < exp_size; ++i) {
        y[i] = exp_data[i];
    }

    auto data = create_data().x(x).y(y);
    auto plt = ax->points(data);

    ax->xlabel("Pred. Target");
    ax->ylabel("Exp. Target");

    // output to svg
    std::ofstream out;
    out.open(dest);
    BackendSVG backend(out);
    fig->draw(backend);
    out.close();
    return 0;
}
```

**Comment by martinjrobins** [comment]
I think the problem is that the `Axis::draw_common_ylabel` uses a fixed offset of 0.05 to shift the ylabel, whereas this offset should be based on the max number of digits in the ytick labels

https://github.com/trase-cpp/trase/blob/a400fe0795edb42b392b699e3517c583056947bf/src/frontend/Axis.tcc#L171

**Comment by martinjrobins** [comment]
Thanks for the issue @zhongjingjogy, feel free to open a PR fixing this, or I will get to it when I can

**Comment by zhongjingjogy** [comment]
I have tried come up with a simple fix. There are problem with number of valid digit in tick values, i.e., the m_sig_digits is fixed as 2. May there be a new issue for developing a feasible strategy for the tick formatter? Thanks again for the nice work! [@martinjrobins](https://github.com/martinjrobins)
