### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fcooper8472** [trase-cpp/trase#27]
Currently this is still
 > Copyright (c) 2018, University of Oxford.

 > This file is part of the Oxford RSE C++ Template project.

Do you want this project to be completely separate from RSE @martinjrobins?  (Might be nice to write a blog post about it anyway).

**Comment by martinjrobins** [comment]
I'd like to keep them separate, but yes, a blog post is a good way to go.

**Comment by martinjrobins** [comment]
closed by #40
