### ISSUE TITLE
Pointers

### ISSUE THREAD

**Issue by fcooper8472** [trase-cpp/trase#32]
I'm still getting to grips with the structure, so might have this wrong.

It looks as though there's a `Drawable` with a vector of children, and a pointer to parent.

Ought this be a vector of `unique_ptr` to children, with a raw pointer to parent?

Also, in `Figure`, is there any need for `m_axis` to be a `shared_ptr` rather than `unique_ptr`?

**Comment by martinjrobins** [comment]
I'm not sure how to do the pointers, so happy to iterate on this.
As you say, each `Drawable` has a vector of children pointers and a pointer to parent
But, each class also has typed pointers to their children (Figure has a Axis pointer, Axis has a vector of Plot1D pointer), so there are two sets of pointers. 

Should the typed children be `unique_ptr`, and all the `Drawable` child pointers and parent pointers be raw? I'm not sure, I haven't had much experience with smart pointers, so you would probably have a better idea

**Comment by martinjrobins** [comment]
also, currently when you create a plot it returns a `std::shared_ptr` so the user can further customise it. But there is no real need for a pointer (it can never be null) so perhaps this should be a reference?

**Comment by fcooper8472** [comment]
I think it might be fairly straightforward.  The chain of ownership is surely just the vector of children?  If a `Plot` has a typed pointer to an `Axis`, say, that Axis is in the `Plot`s vector of children anyway, and we're just peeking in to that vector if we want to hold on to it in the specifically in `Plot`?

So: should `Drawable` have a vector of `unique_ptr`, and absolutely everything else is a raw pointer?

**Comment by martinjrobins** [comment]
This sounds sensible, so the owner of all children would be the base `Drawable` class. Would this call problems when everything gets deleted, since it is the `Drawable` class that deletes the children (which are also `Drawable`?

**Comment by fcooper8472** [comment]
@martinjrobins your thoughts on this:

I had initially gone ahead and changed the method 
```
std::shared_ptr<Axis> axis()
```
to 
```
Axis &axis()
```

But I feel as though users are going to end up with copies if they inadvertently invoke as `Axis ax = fig.axis();` rather than `Axis &ax = fig.axis();`?  Should all our methods that look like this just return raw pointers to the object?  If so, do we worry about users trying to delete them?

**Comment by martinjrobins** [comment]
I hadn't thought that someone might inadvertently copy it, good point. I think you are right that it would be better to return raw pointers. I wouldn't worry about users deleting them, if they do then that is absolutely their fault!
