### ISSUE TITLE
Refactor directory structure

### ISSUE THREAD

**Issue by fcooper8472** [trase-cpp/trase#51]
Proposal to split `src` into the following three directories:

- `backend`
- `frontend`
- `utils`

**Comment by fcooper8472** [comment]
@martinjrobins having some problems with this... `AxisDraw.hpp` (in `src/frontend`) now has:
```cpp
#include "backend/Backend.hpp"
```
which is working fine.  But, `Plot1D.hpp`, for instance (also in `src/frontend`), doesn't compile with
```cpp
#include "util/Colors.hpp"
```
(`fatal error: util/Colors.hpp: No such file or directory`), and seems to need
```cpp
#include "../util/Colors.hpp"
```
instead.  This is the case for all files in `src/util`, but not for any of the frontend or backend files.  Any ideas?

**Comment by martinjrobins** [comment]
That is strange. Surely if `src/` is included in the list of include dirs, the compiler should be able to find `#include "util/Colors.hpp"` from anywhere. Did you check that `src` is actually being included on the command line?

**Comment by fcooper8472** [comment]
Good point!  It's not.  It works when I add the following to `CMakeLists.txt`:
```cmake
target_include_directories (trase PRIVATE ${trase_SOURCE_DIR}/src)
```
I don't understand the `BUILD_INTERFACE` and `INSTALL_INTERFACE` options: should they be included somehow?

**Comment by martinjrobins** [comment]
Its got to do with exporting target once you install Trase somewhere (with make install), the directory structure might change (which it does in our case), which is why you might need to give two directories, one for when you build Trase, and another when you use trase once it is installed

**Comment by martinjrobins** [comment]
e.g. the BUILD_INTERFACE dir struct is:
```
trase/
trase/src
..others, exactly the repo dir structure
```

The INSTALL_INTERFACE dir struct is:
```
install_dir/bin
install_dir/lib
install_dir/include
install_dir/lib
install_dir/font
```
