### ISSUE TITLE
clang-tidy static storage initialisation

### ISSUE THREAD

**Issue by martinjrobins** [trase-cpp/trase#58]
Is the solution to this to add a noexcept to the `Colormap` constructor?

```
/home/travis/build/trase-cpp/trase/src/util/Colors.cpp:126:27: warning: initialization of 'viridis' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]
const Colormap Colormaps::viridis(std::vector<Vector<float, 3>>{
                          ^
/home/travis/build/trase-cpp/trase/src/util/Colors.cpp:107:11: note: possibly throwing constructor declared here
Colormap::Colormap(std::vector<Vector<float, 3>> list)
```

**Comment by fcooper8472** [comment]
I'm not sure.

Making it `noexcept` would appear to be following [this core guideline](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-noexcept), and it removes that clang-tidy warning, so let's go with that.

**Comment by martinjrobins** [comment]
Just added this q to the PR, but I see you have already answered here :) Ok, if its a core guideline then I'm happy to go with that, merging....

**Comment by fcooper8472** [comment]
Ok! I'll close this then.
