### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by martinjrobins** [trase-cpp/trase#70]
Need some sort of online documentation. Listing some options below:

- Exhale (or Breathe) for ReadTheDocs (https://exhale.readthedocs.io/en/latest/overview.html)
- Boost Quickbook (https://www.boost.org/doc/libs/1_67_0/doc/html/quickbook.html)

**Comment by martinjrobins** [comment]
ok, I went for the even simpler option of basic doxygen using codedocs.xyz, output here:

https://codedocs.xyz/martinjrobins/trase/index.html

Setup is amazingly simple, so I'm going to explore this and see how useful basic doxygen is.... what do you think @fcooper8472? I've had a look and Doxygen can do markdown + mathjax, example code (that can be included from actual source files using tags). Seems like everything that I want, only downside is that the pages are kinda dull to look at!

**Comment by fcooper8472** [comment]
Looks good!  I'm all for simplicity.  I'll have a play with this on the weekend too.

**Comment by martinjrobins** [comment]
got auto doxygen documentation with badge link in the readme.md
